version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: debt-tracker-db-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - debt-tracker-network
    restart: unless-stopped
    # Sécurité : ne pas exposer le port en production si vous utilisez un reverse proxy
    # ports:
    #   - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: debt-tracker-server-prod
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - debt-tracker-network
    restart: unless-stopped
    # Limitation des ressources
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: debt-tracker-client-prod
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - debt-tracker-network
    restart: unless-stopped
    # Limitation des ressources
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Reverse proxy avec Nginx (optionnel mais recommandé)
  nginx:
    image: nginx:alpine
    container_name: debt-tracker-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - client
      - server
    networks:
      - debt-tracker-network
    restart: unless-stopped

volumes:
  postgres_data_prod:

networks:
  debt-tracker-network:
    driver: bridge
